package com.asijaandroidsolution.olxappajay.utils

object Constants {
    val DOCUMENT_ID: String?="DOCUMENT_ID"
    val TYPE="TYPE"
    val CATEGORIE_NAME: String="category_name"
    val CURRENCY_SYMBOL= "Rs"
    val CATEGORIES: String="Categories"
    val Id= "Id"
    val CREATED_Date: String = "CREATED_Date"
    val PRICE: String?="PRICE"
    val PHONE: String?="PHONE"
    val ADDRESS: String?="ADDRESS"
    val DESCRIPTION: String?="DESCRIPTION"
    val YEAR: String?="YEAR"
    val BRAND: String?="BRAND"
    val TITLE: String?="TITLE"
    val KEY="KEY"
    val IMAGE_PATH: String?="IMAGE_PATHS"
    val CITY_NAME: String="CITY"
    val USER_ID: String="USER_ID"
    val USER_NAME:String="USER_NAME"
    val PHOTO:String="PHOTO"
    val EMAIL: String="EMAIL"
    val SharedPrefName= "OLXAJAY"
}